// 
// Jenkins Pipeline for iOS projects
//
// Created: 2020/08/26 by Filip Miladinovic
//
// Documentation: https://www.jenkins.io/doc/book/pipeline/syntax/
//


// Global project definitions (should be changed depending on the project)
// def git_credentialId	 	= ''
def git_repository_url  = 'git@github.com:filip982/moviesh-ios.git'
def git_branch 		      = 'master'
def dotenv_environment	= 'default'
// def slack_channel 	    = 'ems_project_template'


// Start jenkins pipeline
pipeline {
	// Configure the running agent
	agent any
	
	// Create additional environment variables to map Jenkins credentials
	environment {
		APPLE_CREDENTIALS 			= credentials('fastlane_apple_id')
		FASTLANE_USER 		  	 	= "${APPLE_CREDENTIALS_USR}"
		FASTLANE_PASSWORD 		 	= "${APPLE_CREDENTIALS_PSW}"
		MATCH_PASSWORD 		 		  = credentials('netconomy_fastlane_match_password')
		MATCH_KEYCHAIN_PASSWORD = credentials('keychain_unlock_password')
	}

	// Stages that will be performed to represend the build flow
	stages {
	
		// Checkout source code from the repository
		stage("Checkout") {
			steps {
				checkout([
					$class: 'GitSCM', 
					branches: [[
						name: "*/${git_branch}"
					]], 
					doGenerateSubmoduleConfigurations: false, 
					extensions: [], 
					submoduleCfg: [], 
					userRemoteConfigs: [[
						# credentialsId: "${git_credentialId}", 
						url: "${git_repository_url}"
					]]
				]) 
			}
		}
		
		// Setup the project (e.g. update cocoapods, download certificates, ...)
		stage("Setup") {
			steps {
				sh """#!/bin/bash -l
					fastlane setup_project --env ${dotenv_environment}
				"""
			}
		}
		
		// Create a build of the application
		stage("Build") {
			steps {
				sh """#!/bin/bash -l
					fastlane build build_number:${BUILD_NUMBER} --env ${dotenv_environment}
				"""
			}
		}
		
		// Deploy the app (e.g. app store, testflight, ...) and abort the stage after 30min (could happen that the uploads gets stuck)
		stage("Deploy") {
			when {
				tag "release/*"
			}
		    options {
		        timeout(time: 20, unit: 'MINUTES') 
		    }
			steps {
				sh """#!/bin/bash -l
					fastlane deploy --env ${dotenv_environment}
				"""
				
				archiveArtifacts(
					artifacts: 'build/*.ipa, build/*.dSYM.zip', 
					followSymlinks: false
				)
			}
		}
		
	}
	
	// Post action will be performed after all stages are completed.
	/*
	post { 
		success { 
			slackSend(
				channel: "${slack_channel}",
				color: '#00FF00',
				message: "${env.JOB_NAME} - #${env.BUILD_NUMBER} Success after ${currentBuild.durationString} (<${env.BUILD_URL}|Open>)"
			)
	    }
		aborted {
			slackSend(
				channel: "${slack_channel}",
				color: '#808080',
				message: "${env.JOB_NAME} - #${env.BUILD_NUMBER} Aborted after ${currentBuild.durationString} (<${env.BUILD_URL}|Open>)"
			)
		}
		failure { 
			slackSend(
				channel: "${slack_channel}",
				color: '#FF0000',
				message: "${env.JOB_NAME} - #${env.BUILD_NUMBER} Failure after ${currentBuild.durationString} (<${env.BUILD_URL}|Open>)"
			)
	    }
		cleanup {
			deleteDir()
		}
	}
	*/
}
